---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: hello-world
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: hello-world-deployment
spec:
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "hello-world-init",
                "image": "hello-world-init:1",
                "command": ["cp", "-a", "/html/.", "/site"],
                "imagePullPolicy": "IfNotPresent",
                "volumeMounts": [
                    {
                        "name": "site",
                        "mountPath": "/site"
                    }
                ]
            }
        ]'
    spec:
      containers:
        - name: hello-world
          image: hello-world-nginx:1
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: site
              mountPath: /usr/share/nginx/html
      volumes:
        - name: site
          emptyDir: {}